In [6]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [7]:
def hisEqulColor(img):
    ycrcb = cv2.cvtColor(img, cv2.COLOR_BGR2YCR_CB)
    channels = cv2.split(ycrcb)
    print(len(channels))
    cv2.equalizeHist(channels[0], channels[0])
    cv2.merge(channels, ycrcb)
    cv2.cvtColor(ycrcb, cv2.COLOR_YCR_CB2BGR, img)
    return img

In [28]:
for num in range(1,196):
    nm = str("%03d" % num)
    
    image = cv2.imread("earImageDataset/"+nm+"_.jpg")
    image = cv2.resize(image,(756,1008))
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    eq = cv2.equalizeHist(gray)         #灰度图片直方图均衡化
    eqc = hisEqulColor(image)
    left_ear_cascade = cv2.CascadeClassifier(r'haarcascade_mcs_rightear.xml')
    if left_ear_cascade.empty():
        raise IOError('Unable to load the left ear cascade classifier xml file')
    xx = 1008
    yy = 1008
    ww = 1008
    hh = 1008
    for i in range(5):
        for j in range(1,100):
            left_ear = left_ear_cascade.detectMultiScale(eq,scaleFactor = (1+j/100),minNeighbors = i,minSize = (200,300))
            if(len(left_ear) == 1):
                for (x,y,w,h) in left_ear:
                    if(x<xx and y<yy):
                        xx = x
                        yy = y
                        ww = w
                        hh = h
    # cv2.rectangle(image, (xx,yy), (xx+ww,yy+hh), (0,255,0), 3)
    # cv2.imshow('Ear Detector', cv2.resize(image,(378,504)))
    # cv2.imshow('Ear Only', )
    cv2.imwrite("cropedEar/" + nm + "_.jpg" ,eq[yy:yy+hh,xx:xx+ww])
    
    
    image = cv2.imread("earImageDataset/"+nm+"_t.jpg")
    image = cv2.resize(image,(756,1008))
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    eq = cv2.equalizeHist(gray)         #灰度图片直方图均衡化
    left_ear_cascade = cv2.CascadeClassifier(r'haarcascade_mcs_rightear.xml')
    if left_ear_cascade.empty():
        raise IOError('Unable to load the left ear cascade classifier xml file')
    xx = 1008
    yy = 1008
    ww = 1008
    hh = 1008
    for i in range(5):
        for j in range(1,100):
            left_ear = left_ear_cascade.detectMultiScale(eq,scaleFactor = (1+j/100),minNeighbors = i,minSize = (200,300))
            if(len(left_ear) == 1):
                for (x,y,w,h) in left_ear:
                    if(x<xx and y<yy):
                        xx = x
                        yy = y
                        ww = w
                        hh = h
    # cv2.rectangle(image, (xx,yy), (xx+ww,yy+hh), (0,255,0), 3)
    # cv2.imshow('Ear Detector', cv2.resize(image,(378,504)))
    # cv2.imshow('Ear Only', )
    
    cv2.imwrite("cropedEar/" + nm + "_t.jpg" ,eq[yy:yy+hh,xx:xx+ww])

    image = cv2.imread("earImageDataset/"+nm+"_d.jpg")
    image = cv2.resize(image,(756,1008))
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    eq = cv2.equalizeHist(gray)         #灰度图片直方图均衡化
    left_ear_cascade = cv2.CascadeClassifier(r'haarcascade_mcs_rightear.xml')
    if left_ear_cascade.empty():
        raise IOError('Unable to load the left ear cascade classifier xml file')
    xx = 1008
    yy = 1008
    ww = 1008
    hh = 1008
    for i in range(5):
        for j in range(1,100):
            left_ear = left_ear_cascade.detectMultiScale(eq,scaleFactor = (1+j/100),minNeighbors = i,minSize = (200,300))
            if(len(left_ear) == 1):
                for (x,y,w,h) in left_ear:
                    if(x<xx and y<yy):
                        xx = x
                        yy = y
                        ww = w
                        hh = h
    # cv2.rectangle(image, (xx,yy), (xx+ww,yy+hh), (0,255,0), 3)
    # cv2.imshow('Ear Detector', cv2.resize(image,(378,504)))
    # cv2.imshow('Ear Only', )
    cv2.imwrite("cropedEar/" + nm + "_d.jpg" ,eq[yy:yy+hh,xx:xx+ww])
    
    image = cv2.imread("earImageDataset/"+nm+"_dt.jpg")
    image = cv2.resize(image,(756,1008))
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    eq = cv2.equalizeHist(gray)         #灰度图片直方图均衡化
    left_ear_cascade = cv2.CascadeClassifier(r'haarcascade_mcs_rightear.xml')
    if left_ear_cascade.empty():
        raise IOError('Unable to load the left ear cascade classifier xml file')
    xx = 1008
    yy = 1008
    ww = 1008
    hh = 1008
    for i in range(5):
        for j in range(1,100):
            left_ear = left_ear_cascade.detectMultiScale(eq,scaleFactor = (1+j/100),minNeighbors = i,minSize = (200,300))
            if(len(left_ear) == 1):
                for (x,y,w,h) in left_ear:
                    if(x<xx and y<yy):
                        xx = x
                        yy = y
                        ww = w
                        hh = h
    # cv2.rectangle(image, (xx,yy), (xx+ww,yy+hh), (0,255,0), 3)
    # cv2.imshow('Ear Detector', cv2.resize(image,(378,504)))
    # cv2.imshow('Ear Only', )
    cv2.imwrite("cropedEar/" + nm + "_dt.jpg" ,eq[yy:yy+hh,xx:xx+ww])


3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3


In [27]:
image = cv2.imread("earImageDataset/"+str(192)+"_dt.jpg")
image = cv2.resize(image,(756,1008))
print(image.shape)
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
eq = cv2.equalizeHist(gray)         #灰度图片直方图均衡化
eqc = hisEqulColor(image)
left_ear_cascade = cv2.CascadeClassifier(r'haarcascade_mcs_rightear.xml')
if left_ear_cascade.empty():
    raise IOError('Unable to load the left ear cascade classifier xml file')
xx = 1008
yy = 1008
ww = 1008
hh = 1008
for i in range(5):
    for j in range(1,100):
        left_ear = left_ear_cascade.detectMultiScale(eq,scaleFactor = (1+j/100),minNeighbors = i,minSize = (200,300))
        if(len(left_ear) == 1):
            for (x,y,w,h) in left_ear:
                if(x<xx and y<yy):
                    xx = x
                    yy = y
                    ww = w
                    hh = h
# cv2.rectangle(image, (xx,yy), (xx+ww,yy+hh), (0,255,0), 3)
# cv2.imshow('Ear Detector', cv2.resize(image,(378,504)))
# cv2.imshow('Ear Only', )
print(eqc.shape)
croped = image[yy:yy+hh,xx:xx+ww,:]
print(croped)
croped = cv2.resize(croped,(256,256))
cv2.imwrite("cropedEar/" + nm + "_dt.jpg" ,croped)

(1008, 756, 3)
3
(1008, 756, 3)
[[[158 109 101]
  [158 109 101]
  [158 109 101]
  ...
  [112  85  89]
  [112  85  89]
  [ 92  65  69]]

 [[158 109 101]
  [154 105  97]
  [154 105  97]
  ...
  [107  80  84]
  [107  80  84]
  [117  90  94]]

 [[151 102  94]
  [154 105  97]
  [154 105  97]
  ...
  [116  89  93]
  [100  73  77]
  [112  85  89]]

 ...

 [[152 119 116]
  [152 119 116]
  [152 119 116]
  ...
  [ 26  10   4]
  [ 26  10   4]
  [ 26  10   4]]

 [[152 119 116]
  [152 119 116]
  [152 119 116]
  ...
  [ 26  10   4]
  [ 26  10   4]
  [ 26  10   4]]

 [[156 123 120]
  [138 105 102]
  [166 133 130]
  ...
  [ 26  10   4]
  [ 26  10   4]
  [ 36  20  14]]]


True